version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_db
    environment:
      - MONGO_INITDB_DATABASE=rss
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
